name: Android_CI

on:
  push:
    branches:
      - beta_release

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build release-apk and deploy to PlayMarket
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      #      # Without NDK not compile and not normal error message. NDK is required
      #      - name: Install NDK
      #        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
      # Some times is have problems with permissions for ./gradle file. Then uncommit it code
      #    - name: Make gradlew executable
      #      run: chmod +x ./gradlew
      - name: Output version code
        run: echo VERSION_CODE=${{ github.run_number }} > ./version.properties
      - name: Build with Gradle
        run: ./gradlew build -release
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          PIN_ALIAS: ${{ secrets.PIN_ALIAS }}
          DB_PASS_ALIAS: ${{ secrets.DB_PASS_ALIAS }}
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: notification_tracker
          path: app/build/outputs/apk/release/notification_tracker.release.apk
      - name: Upload to PlayMarket
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.guralnya.notification_tracker
          releaseFile: app/build/outputs/apk/release/notification_tracker.release.apk
          track: beta
          whatsNewDirectory: distribution/whatsnew
